#!/bin/bash
#
# Station Quick Setup bootstrap.
#
# Fetched and executed by the one-line Setup_Command generated by the Edge CV
# Portal. It is intentionally small and self-contained (no bundle dependencies):
# the Setup_Command has already verified THIS script's checksum before running
# it, and this script in turn is the integrity anchor for everything that
# follows (command -> verifies bootstrap -> bootstrap verifies bundle).
#
# Responsibilities (see station-quick-setup design section 7):
#   1. Preflight prerequisite checks. Print EVERY unmet prerequisite and exit
#      non-zero with NO system changes (Req 7.1, 7.2).
#   2. POST the Setup_Token to the /bundle endpoint to obtain the bundle
#      manifest. On invalid/expired token, print the regenerate instruction and
#      exit non-zero (Req 7.5).
#   3. Download the bundle to a temp dir and verify it against the manifest
#      SHA-256. On mismatch, print an integrity error, delete the download, and
#      exit non-zero WITHOUT extracting or executing anything (Req 4.8, 4.9).
#   4. Extract the bundle and exec run.sh with the manifest parameters exported
#      as DDA_* environment variables.
#
# Usage: bootstrap.sh --endpoint <quick-setup-url> --token <setup-token>

set -u

# --- constants ---------------------------------------------------------------

MIN_FREE_KB=2097152                       # 2 GB in KB
SUPPORTED_ARCHS="x86_64 aarch64"
SUPPORTED_UBUNTU="18.04 20.04 22.04 24.04"

# --- argument parsing --------------------------------------------------------

ENDPOINT=""
TOKEN=""

usage() {
    echo "Usage: bootstrap.sh --endpoint <quick-setup-url> --token <setup-token>" >&2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --endpoint)
            ENDPOINT="${2:-}"
            shift 2 || { usage; exit 2; }
            ;;
        --endpoint=*)
            ENDPOINT="${1#*=}"
            shift
            ;;
        --token)
            TOKEN="${2:-}"
            shift 2 || { usage; exit 2; }
            ;;
        --token=*)
            TOKEN="${1#*=}"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "❌ Unknown argument: $1" >&2
            usage
            exit 2
            ;;
    esac
done

if [ -z "$ENDPOINT" ] || [ -z "$TOKEN" ]; then
    echo "❌ Both --endpoint and --token are required." >&2
    usage
    exit 2
fi

# Normalize: strip any trailing slash so "${ENDPOINT}/bundle" is well formed.
ENDPOINT="${ENDPOINT%/}"

# --- HTTP helpers (curl preferred, wget fallback) ----------------------------

HTTP_TOOL=""
if command -v curl >/dev/null 2>&1; then
    HTTP_TOOL="curl"
elif command -v wget >/dev/null 2>&1; then
    HTTP_TOOL="wget"
fi

# http_post <url> <json-body> <out-body-file>
# Writes the response body to <out-body-file>. Echoes the HTTP status code to
# stdout. Returns non-zero only on a transport-level failure.
http_post() {
    local url="$1" body="$2" out="$3" code=""
    if [ "$HTTP_TOOL" = "curl" ]; then
        code=$(curl -sS -o "$out" -w '%{http_code}' \
            -X POST -H 'Content-Type: application/json' \
            --data "$body" "$url" 2>/dev/null)
        local rc=$?
        echo "$code"
        return $rc
    else
        # wget writes the body to <out>; capture status from the server response
        # headers via -S (printed on stderr).
        local hdrs
        hdrs=$(wget -q -O "$out" -S --header='Content-Type: application/json' \
            --post-data="$body" "$url" 2>&1)
        local rc=$?
        code=$(printf '%s\n' "$hdrs" | grep -oE 'HTTP/[0-9.]+ [0-9]{3}' | tail -1 | awk '{print $2}')
        [ -z "$code" ] && { [ $rc -eq 0 ] && code="200" || code="000"; }
        echo "$code"
        return 0
    fi
}

# http_download <url> <out-file>
http_download() {
    local url="$1" out="$2"
    if [ "$HTTP_TOOL" = "curl" ]; then
        curl -fsSL -o "$out" "$url"
    else
        wget -q -O "$out" "$url"
    fi
}

# --- minimal JSON field extraction -------------------------------------------
# The manifest is a small, server-controlled JSON document with flat string
# fields, so a targeted extractor avoids a hard dependency on jq/python.

# json_string <file> <key> -> value of a top-level or nested string field.
json_string() {
    local file="$1" key="$2"
    # Matches  "key" : "value"  capturing value (no escaped quotes expected).
    grep -oE "\"$key\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$file" \
        | head -1 \
        | sed -E "s/.*\"$key\"[[:space:]]*:[[:space:]]*\"([^\"]*)\".*/\1/"
}

# --- prerequisite checks (NO system changes) ---------------------------------

UNMET=()

check_prerequisites() {
    # HTTP client: curl or wget.
    if [ -z "$HTTP_TOOL" ]; then
        UNMET+=("Missing required tool: curl or wget (need at least one)")
    fi

    # sha256sum for bundle integrity verification.
    if ! command -v sha256sum >/dev/null 2>&1; then
        UNMET+=("Missing required tool: sha256sum")
    fi

    # tar to extract the downloaded bundle.
    if ! command -v tar >/dev/null 2>&1; then
        UNMET+=("Missing required tool: tar")
    fi

    # Root privileges (provisioning installs system packages and services).
    if [ "$(id -u)" -ne 0 ]; then
        UNMET+=("Root privileges required (re-run with sudo)")
    fi

    # Supported Ubuntu release.
    if ! command -v lsb_release >/dev/null 2>&1; then
        UNMET+=("Cannot determine OS release: lsb_release not found (Ubuntu required)")
    else
        local distro release
        distro=$(lsb_release -is 2>/dev/null)
        release=$(lsb_release -rs 2>/dev/null)
        if [ "$distro" != "Ubuntu" ]; then
            UNMET+=("Unsupported OS: '$distro' (Ubuntu required)")
        elif ! printf '%s\n' $SUPPORTED_UBUNTU | grep -qx "$release"; then
            UNMET+=("Unsupported Ubuntu release: '$release' (supported: $SUPPORTED_UBUNTU)")
        fi
    fi

    # Supported CPU architecture.
    local arch
    arch=$(uname -m 2>/dev/null)
    if ! printf '%s\n' $SUPPORTED_ARCHS | grep -qx "$arch"; then
        UNMET+=("Unsupported CPU architecture: '$arch' (supported: $SUPPORTED_ARCHS)")
    fi

    # At least 2 GB free on the root filesystem.
    local free_kb
    free_kb=$(df -Pk / 2>/dev/null | awk 'NR==2 {print $4}')
    if [ -z "$free_kb" ]; then
        UNMET+=("Could not determine free disk space on /")
    elif [ "$free_kb" -lt "$MIN_FREE_KB" ]; then
        UNMET+=("Insufficient free disk space on / (need >=2GB, have $(( free_kb / 1024 ))MB)")
    fi
}

echo "▶ Checking station prerequisites..."
check_prerequisites

if [ ${#UNMET[@]} -gt 0 ]; then
    echo "" >&2
    echo "❌ Prerequisite checks failed. No changes were made to this system." >&2
    for item in "${UNMET[@]}"; do
        echo "  - $item" >&2
    done
    exit 1
fi
echo "✓ Prerequisites satisfied"

# --- request the bundle manifest ---------------------------------------------

REGENERATE_MSG="Generate a new setup command from the Edge CV Portal and run it again."

MANIFEST_FILE=$(mktemp)
cleanup_manifest() { rm -f "$MANIFEST_FILE"; }
trap cleanup_manifest EXIT

echo "▶ Requesting setup bundle..."
STATUS=$(http_post "${ENDPOINT}/bundle" "{\"token\": \"${TOKEN}\"}" "$MANIFEST_FILE")

if [ "$STATUS" != "200" ]; then
    # The endpoint returns 403 for invalid/expired tokens with an error code in
    # the body; any non-200 means we cannot proceed.
    err_code=$(json_string "$MANIFEST_FILE" "error")
    case "$err_code" in
        invalid_token|token_expired)
            echo "❌ The setup token is not valid or has expired." >&2
            ;;
        *)
            echo "❌ Failed to obtain the setup bundle (HTTP ${STATUS})." >&2
            ;;
    esac
    echo "   $REGENERATE_MSG" >&2
    exit 1
fi

BUNDLE_URL=$(json_string "$MANIFEST_FILE" "bundle_url")
BUNDLE_SHA256=$(json_string "$MANIFEST_FILE" "bundle_sha256")
P_REGISTRATION_ID=$(json_string "$MANIFEST_FILE" "registration_id")
P_DEVICE_NAME=$(json_string "$MANIFEST_FILE" "device_name")
P_DEVICE_GROUP=$(json_string "$MANIFEST_FILE" "device_group")
P_AWS_REGION=$(json_string "$MANIFEST_FILE" "aws_region")
P_QS_URL=$(json_string "$MANIFEST_FILE" "quick_setup_url")

if [ -z "$BUNDLE_URL" ] || [ -z "$BUNDLE_SHA256" ]; then
    echo "❌ The setup bundle manifest is incomplete." >&2
    echo "   $REGENERATE_MSG" >&2
    exit 1
fi

# --- download and verify the bundle ------------------------------------------

WORKDIR=$(mktemp -d)
cleanup_all() { rm -f "$MANIFEST_FILE"; rm -rf "$WORKDIR"; }
trap cleanup_all EXIT

BUNDLE_TGZ="${WORKDIR}/setup-bundle.tar.gz"

echo "▶ Downloading setup bundle..."
if ! http_download "$BUNDLE_URL" "$BUNDLE_TGZ"; then
    echo "❌ Failed to download the setup bundle." >&2
    exit 1
fi

echo "▶ Verifying bundle integrity..."
if ! echo "${BUNDLE_SHA256}  ${BUNDLE_TGZ}" | sha256sum -c - >/dev/null 2>&1; then
    # Integrity failure: delete the download and refuse to extract or execute
    # any part of the bundle (Req 4.9).
    rm -f "$BUNDLE_TGZ"
    echo "❌ Setup bundle integrity check FAILED (checksum mismatch)." >&2
    echo "   The download was discarded and nothing was extracted or executed." >&2
    exit 1
fi
echo "✓ Bundle integrity verified"

# --- extract and hand off to run.sh ------------------------------------------

echo "▶ Extracting setup bundle..."
EXTRACT_DIR="${WORKDIR}/bundle"
mkdir -p "$EXTRACT_DIR"
if ! tar -xzf "$BUNDLE_TGZ" -C "$EXTRACT_DIR"; then
    echo "❌ Failed to extract the setup bundle." >&2
    exit 1
fi

RUN_SH=$(find "$EXTRACT_DIR" -type f -path '*quick_setup/run.sh' 2>/dev/null | head -1)
if [ -z "$RUN_SH" ] || [ ! -f "$RUN_SH" ]; then
    echo "❌ The setup bundle is missing its run.sh entrypoint." >&2
    exit 1
fi
chmod +x "$RUN_SH" 2>/dev/null || true

# Release the WORKDIR trap so the extracted bundle survives into run.sh, which
# owns its own cleanup (including credential material, Req 5.6).
trap cleanup_manifest EXIT

echo "▶ Starting provisioning..."
export DDA_REGISTRATION_ID="$P_REGISTRATION_ID"
export DDA_DEVICE_NAME="$P_DEVICE_NAME"
export DDA_THING_GROUP="$P_DEVICE_GROUP"
export DDA_AWS_REGION="$P_AWS_REGION"
export DDA_QS_URL="$P_QS_URL"
export DDA_SETUP_TOKEN="$TOKEN"

exec bash "$RUN_SH"
