"""Workflow_Validator: structural and semantic graph validation.

Runs all checks (input/output presence, connection port compatibility,
cycle detection, required parameters, reachability, warnings) and returns
the complete list of ValidationFinding records.
"""

from .checks import (
    CODE_MODEL_REF_UNRESOLVED,
    CODE_UNKNOWN_NODE_TYPE,
    CODE_V1_NO_INPUT_NODE,
    CODE_V1_NO_OUTPUT_NODE,
    CODE_V2_INCOMPATIBLE_TYPES,
    CODE_V2_SOURCE_NOT_OUTPUT,
    CODE_V2_TARGET_NOT_INPUT,
    CODE_V2_UNKNOWN_NODE,
    CODE_V2_UNKNOWN_PORT,
    CODE_V3_CYCLE,
    CODE_V4_INVALID_PARAMETER_VALUE,
    CODE_V4_MISSING_REQUIRED_PARAMETER,
    CODE_V5_UNREACHABLE_NODE,
    CODE_W1_OUTPUT_NODE_NO_INPUT,
    CODE_W1_UNUSED_OUTPUT_PORT,
    MODEL_TYPE_VLLM,
    SEVERITY_ERROR,
    SEVERITY_WARNING,
    TYPE_LLM_INFERENCE,
    ValidationFinding,
    validate,
)
from .parameters import (
    ParameterViolation,
    VIOLATION_MAX,
    VIOLATION_MAX_LENGTH,
    VIOLATION_MIN,
    VIOLATION_MIN_EXCLUSIVE,
    VIOLATION_MIN_LENGTH,
    VIOLATION_REGEX,
    VIOLATION_REQUIRED,
    VIOLATION_TYPE,
    VIOLATION_UNKNOWN_TYPE,
    VIOLATION_VALUES,
    check_parameter_value,
    is_parameter_value_valid,
)

__all__ = [
    # validate() and findings
    "validate",
    "ValidationFinding",
    "SEVERITY_ERROR",
    "SEVERITY_WARNING",
    "CODE_UNKNOWN_NODE_TYPE",
    "CODE_V1_NO_INPUT_NODE",
    "CODE_V1_NO_OUTPUT_NODE",
    "CODE_V2_UNKNOWN_NODE",
    "CODE_V2_UNKNOWN_PORT",
    "CODE_V2_SOURCE_NOT_OUTPUT",
    "CODE_V2_TARGET_NOT_INPUT",
    "CODE_V2_INCOMPATIBLE_TYPES",
    "CODE_V3_CYCLE",
    "CODE_V4_MISSING_REQUIRED_PARAMETER",
    "CODE_V4_INVALID_PARAMETER_VALUE",
    "CODE_V5_UNREACHABLE_NODE",
    "CODE_W1_OUTPUT_NODE_NO_INPUT",
    "CODE_W1_UNUSED_OUTPUT_PORT",
    "CODE_MODEL_REF_UNRESOLVED",
    "MODEL_TYPE_VLLM",
    "TYPE_LLM_INFERENCE",
    # parameter predicate
    "ParameterViolation",
    "check_parameter_value",
    "is_parameter_value_valid",
    "VIOLATION_REQUIRED",
    "VIOLATION_TYPE",
    "VIOLATION_MIN",
    "VIOLATION_MIN_EXCLUSIVE",
    "VIOLATION_MAX",
    "VIOLATION_MIN_LENGTH",
    "VIOLATION_MAX_LENGTH",
    "VIOLATION_REGEX",
    "VIOLATION_VALUES",
    "VIOLATION_UNKNOWN_TYPE",
]
