"""The sandbox half of the Scene_Analytics parity test.

**Feature: rtsp-rtmp-stream-cameras, Property 27: Analytics parity between
the device and the sandbox** — *for any* Detection_List, analytics
parameters, frame size and outcome sequence, the LocalServer bindings and
the sandbox bindings produce identical ``counter``, ``association`` and
``event`` metadata.

**Validates: Requirements 13.9, 14.6, 15.6**

Every case of the shared fixture (``fixtures/analytics_parity_cases.json``,
generated by ``analytics_parity_fixtures.py`` from an oracle over the
shared ``workflow_core.analytics.scene`` module) is replayed through
``harness.bindings.run_scene_analytics``, carrying each gate's state from
run to run exactly as the device does across a registration's runs. The
device half (task 21.3) replays the same file through the LocalServer
bindings, so agreeing with the fixture makes the two agree.

A sandbox test run is a single run, so the second test replays each case's
first run through ``execute_bindings`` — the entry point the harness
calls — where every gate starts inactive (Requirement 15.6).
"""
import copy
import json
import os
import sys

import pytest

_TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
_TEST_SANDBOX_DIR = os.path.dirname(_TESTS_DIR)
_WORKFLOW_CORE_PYTHON = os.path.join(
    os.path.dirname(_TEST_SANDBOX_DIR), "backend", "layers", "workflow_core", "python")
if _TEST_SANDBOX_DIR not in sys.path:
    sys.path.insert(0, _TEST_SANDBOX_DIR)
# Appended, not prepended (see analytics_parity_fixtures._ensure_paths).
if _WORKFLOW_CORE_PYTHON not in sys.path:
    sys.path.append(_WORKFLOW_CORE_PYTHON)

from harness.bindings import execute_bindings, run_scene_analytics  # noqa: E402
from harness.results import ResultsStore  # noqa: E402

FIXTURE_PATH = os.path.join(_TESTS_DIR, "fixtures", "analytics_parity_cases.json")

with open(FIXTURE_PATH, encoding="utf-8") as _handle:
    CASES = json.load(_handle)["cases"]

SECTIONS = ("counter", "association", "event")


def run_metadata(run):
    metadata = dict(run["tags"])
    if run["detections"] is not None:
        metadata["detections"] = copy.deepcopy(run["detections"])
    return metadata


@pytest.mark.parametrize("case", CASES, ids=[case["name"] for case in CASES])
def test_every_run_reproduces_the_shared_metadata(case):
    states = None
    for number, run in enumerate(case["runs"]):
        metadata = run_metadata(run)
        before = copy.deepcopy(metadata)
        result = run_scene_analytics(case["bindings"], metadata,
                                     frame_size=case["frameSize"],
                                     states=states, now_ms=run["nowMs"])
        where = f"{case['name']}, run {number}"
        produced = {key: result.metadata[key] for key in SECTIONS
                    if key in result.metadata}
        assert produced == run["expected"], where
        assert result.outcomes == run["outcomes"], where
        assert result.passed == run["passed"], where
        # The input metadata is not mutated.
        assert metadata == before, where
        states = result.states


@pytest.mark.parametrize("case", CASES, ids=[case["name"] for case in CASES])
def test_a_test_run_starts_every_gate_inactive(case):
    """Through the harness entry point, each call is a fresh test run: the
    first run's metadata, whatever came before it in the fixture."""
    first = case["runs"][0]
    for _attempt in range(2):
        node_ids = [binding["nodeId"] for binding in case["bindings"]]
        store = ResultsStore(node_ids)
        detections = first["detections"]
        execute_bindings(case["bindings"], dict(first["tags"]), store,
                         detections=copy.deepcopy(detections)
                         if detections is not None else None,
                         frame_size=case["frameSize"], now_ms=first["nowMs"])
        document = {record["nodeId"]: record for record in store.to_document()["nodes"]}
        for binding in case["bindings"]:
            record = document[binding["nodeId"]]
            # Analytics never fail a test run (Requirement 13.6).
            assert record["status"] == "completed", record
            (output,) = record["outputs"]
            node_id = binding["nodeId"]
            if binding["binding"] == "event_gate":
                if first["detections"] is None:
                    # The harness substitutes an empty Detection_List, so
                    # only a run that had one is comparable here.
                    continue
                assert output["metadata"] == first["expected"]["event"][node_id]
                assert output["passed"] == first["passed"][node_id]
            elif first["detections"] is not None:
                section = ("counter" if binding["binding"] == "detection_counter"
                           else "association")
                assert output["metadata"] == first["expected"][section][node_id]
                assert output["outcome"] == first["outcomes"][node_id]
