#
#  Copyright 2025 Amazon Web Services, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import time
from typing import Callable

from fastapi import APIRouter, Request, Response, HTTPException, Depends
from fastapi.routing import APIRoute
import structlog
from asgi_correlation_id.context import correlation_id
from starlette.background import BackgroundTask
from uvicorn.protocols.utils import get_path_with_query_string

import logging

from utils import utils
from utils.auth import validate_token

logger = logging.getLogger(__name__)

access_logger = structlog.stdlib.get_logger("api.access")

def log_info(process_time_ns, req_body, status_code):
    structlog.contextvars.clear_contextvars()
    # These context vars will be added to all log entries emitted during the request
    request_id = correlation_id.get()
    structlog.contextvars.bind_contextvars(request_id=request_id)

    url = get_path_with_query_string(req_body.scope)
    client_host = req_body.client.host
    client_port = req_body.client.port
    http_method = req_body.method
    http_version = req_body.scope["http_version"]

    access_logger.info(
        f"""{client_host}:{client_port} - "{http_method} {url} HTTP/{http_version}" {status_code}""",
        http={
            "url": url,
            "status_code": status_code,
            "method": http_method,
            "request_id": request_id,
            "version": http_version,
        },
        network={"client": {"ip": client_host, "port": client_port}},
        duration=f"{process_time_ns / 10 ** 6}ms",
    )

# This wraps the normal router to add some custom functionality around every request, a-la Coral Interceptor.
# https://fastapi.tiangolo.com/how-to/custom-request-and-route/#custom-request-and-apiroute-class
class AccessLogRoute(APIRoute):
    def get_route_handler(self) -> Callable:
        original_route_handler = super().get_route_handler()

        async def custom_route_handler(request: Request) -> Response:

            start_time_ns = time.perf_counter_ns()
            try:
                response: Response = await original_route_handler(request)
                process_time_ns = time.perf_counter_ns() - start_time_ns
                log_info(process_time_ns, request, response.status_code)
                response.headers["X-Process-Time"] = str(process_time_ns / 10 ** 9)
                return response
            except Exception as e:
                process_time_ns = time.perf_counter_ns() - start_time_ns
                '''
                    HTTPException is a wrapper around all expected exceptions, generated by FastAPI which adds 
                    status_code as a property. This basically means all exceptions that are expected will have
                    status_code set. Otherwise default to generic 5XX which is 500.
                '''
                status_code = e.status_code if isinstance(e, HTTPException) else 500
                log_info(process_time_ns, request, status_code)
                raise e

        return custom_route_handler


def get_api_router():
    if utils.is_authorization_enabled_on_station():
        return APIRouter(route_class=AccessLogRoute, dependencies=[Depends(validate_token)])
    return APIRouter(route_class=AccessLogRoute)
