#
#  Copyright 2025 Amazon Web Services, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import time
from typing import Callable

from fastapi import APIRouter, Request, Response, HTTPException, Depends
from fastapi.routing import APIRoute
import structlog
from asgi_correlation_id.context import correlation_id
from starlette.background import BackgroundTask
from uvicorn.protocols.utils import get_path_with_query_string

import logging

from utils.auth import authorize_request

logger = logging.getLogger(__name__)

access_logger = structlog.stdlib.get_logger("api.access")

def log_info(process_time_ns, req_body, status_code):
    structlog.contextvars.clear_contextvars()
    # These context vars will be added to all log entries emitted during the request
    request_id = correlation_id.get()
    structlog.contextvars.bind_contextvars(request_id=request_id)

    url = get_path_with_query_string(req_body.scope)
    # ``Request.client`` is None whenever the ASGI scope carries no peer address.
    # Uvicorn's ProxyHeadersMiddleware rewrites scope["client"], and a transport
    # that exposes no peername leaves it unset, so this is reachable in normal
    # operation -- it is not a "cannot happen" case.
    #
    # Dereferencing it unguarded took the entire backend down on a Jetson Thor
    # (DLAP-701) after a reboot: a workflow component POSTing
    # /workflows/registrations arrived with client=None, log_info raised
    # AttributeError AFTER the route had already returned 200, the except branch
    # in AccessLogRoute called log_info a second time so it raised again, and
    # each escaping exception then spent ~45 s of GIL inside structlog's rich
    # traceback renderer pretty-printing the whole ASGI scope. Requests arrived
    # faster than they drained, so /health and the model components' StartModel
    # calls all timed out and the blue-plate model never reached READY.
    #
    # Access logging must never be able to fail the request it is logging.
    client = req_body.client
    client_host = client.host if client is not None else None
    client_port = client.port if client is not None else None
    http_method = req_body.method
    http_version = req_body.scope["http_version"]

    # "-" for an absent peer, following the common access-log convention, while
    # the structured network.client fields stay None rather than a fake value.
    display_host = client_host if client_host is not None else "-"
    display_port = client_port if client_port is not None else "-"

    access_logger.info(
        f"""{display_host}:{display_port} - "{http_method} {url} HTTP/{http_version}" {status_code}""",
        http={
            "url": url,
            "status_code": status_code,
            "method": http_method,
            "request_id": request_id,
            "version": http_version,
        },
        network={"client": {"ip": client_host, "port": client_port}},
        duration=f"{process_time_ns / 10 ** 6}ms",
    )

# This wraps the normal router to add some custom functionality around every request, a-la Coral Interceptor.
# https://fastapi.tiangolo.com/how-to/custom-request-and-route/#custom-request-and-apiroute-class
class AccessLogRoute(APIRoute):
    def get_route_handler(self) -> Callable:
        original_route_handler = super().get_route_handler()

        async def custom_route_handler(request: Request) -> Response:

            start_time_ns = time.perf_counter_ns()
            try:
                response: Response = await original_route_handler(request)
                process_time_ns = time.perf_counter_ns() - start_time_ns
                log_info(process_time_ns, request, response.status_code)
                response.headers["X-Process-Time"] = str(process_time_ns / 10 ** 9)
                return response
            except Exception as e:
                process_time_ns = time.perf_counter_ns() - start_time_ns
                '''
                    HTTPException is a wrapper around all expected exceptions, generated by FastAPI which adds 
                    status_code as a property. This basically means all exceptions that are expected will have
                    status_code set. Otherwise default to generic 5XX which is 500.
                '''
                status_code = e.status_code if isinstance(e, HTTPException) else 500
                log_info(process_time_ns, request, status_code)
                raise e

        return custom_route_handler


def get_api_router():
    # authorize_request is attached unconditionally: it evaluates the
    # (Local_Login_Configuration x Existing_Token_Auth) decision matrix per
    # request instead of freezing the decision at import time, so runtime
    # configuration changes take effect without a restart (Requirement 11.2).
    # The (disabled, not-configured) row allows every request, preserving
    # today's open-access behavior exactly (Requirements 9.1, 9.3).
    return APIRouter(route_class=AccessLogRoute, dependencies=[Depends(authorize_request)])
