#!/usr/bin/env bash
# Build (and optionally push) the Export_Image for imported detector
# checkpoints (spec: .kiro/specs/detector-checkpoint-import, design.md §3).
#
# Usage:
#   ./build-and-push.sh --lock                     # re-resolve requirements.lock / ort-floor.lock
#   ./build-and-push.sh --build [--tag TAG]        # build locally as dda-detector-export:TAG
#   ./build-and-push.sh --push  [--tag TAG] [--repo NAME] [--region R] [--account ID]
#                                                   # build, push to ECR, print the @sha256 URI
#
# The printed "@sha256" URI is what the portal deploy takes:
#   -c detectorExportImage=<account>.dkr.ecr.<region>.amazonaws.com/dda-detector-export@sha256:<digest>
#
# Only a minimal, staged context is sent to the builder (this directory's
# Dockerfile + locks and the three entry-point modules from
# datasets/detection_training/) -- never the repository root.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
CODE_DIR="$REPO_ROOT/datasets/detection_training"
ENGINE="${CONTAINER_ENGINE:-docker}"
BASE_IMAGE="$(sed -n 's/^ARG BASE_IMAGE=//p' "$HERE/Dockerfile")"

MODE=""
TAG="${TAG:-$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || date +%Y%m%d%H%M%S)}"
ECR_REPO="${ECR_REPO:-dda-detector-export}"
AWS_REGION="${AWS_REGION:-us-east-1}"
AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-}"

while [ $# -gt 0 ]; do
  case "$1" in
    --lock|--build|--push) MODE="${1#--}"; shift ;;
    --tag) TAG="$2"; shift 2 ;;
    --repo) ECR_REPO="$2"; shift 2 ;;
    --region) AWS_REGION="$2"; shift 2 ;;
    --account) AWS_ACCOUNT_ID="$2"; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$MODE" ] || { echo "one of --lock / --build / --push is required" >&2; exit 2; }

lock() {
  # Resolve inside the pinned base image with network ON (build time only) and
  # rewrite both lock files, keeping their header comments.
  local out
  out="$("$ENGINE" run --rm -v "$HERE":/src:ro "$BASE_IMAGE" bash -lc '
    set -e
    export PIP_DISABLE_PIP_VERSION_CHECK=1 PIP_NO_CACHE_DIR=1 PIP_ROOT_USER_ACTION=ignore
    python -m venv /opt/ort-floor >/dev/null
    /opt/ort-floor/bin/pip install -q "onnxruntime==1.16.3" "numpy<2"
    echo "=== ORT-FLOOR"
    /opt/ort-floor/bin/pip freeze
    pip install -q --index-url https://download.pytorch.org/whl/cpu torch==2.5.1+cpu torchvision==0.20.1+cpu
    grep -v -E "^(torch|torchvision)==" /src/requirements.in | grep -v -E "^\s*(#|$)" > /tmp/top.txt
    printf "torch==2.5.1+cpu\ntorchvision==0.20.1+cpu\n" > /tmp/constraints.txt
    pip install -q -r /tmp/top.txt -c /tmp/constraints.txt --extra-index-url https://download.pytorch.org/whl/cpu
    pip check > /dev/null
    echo "=== MAIN"
    pip freeze | grep -v -E "^(torch|torchvision)=="
  ')"
  {
    sed -n '/^#/p' "$HERE/ort-floor.lock"
    printf '%s\n' "$out" | sed -n '/^=== ORT-FLOOR$/,/^=== /p' | grep -v '^==='
  } > "$HERE/ort-floor.lock.new"
  {
    echo "# GENERATED by build-and-push.sh --lock from requirements.in -- do not edit by hand."
    echo "# torch / torchvision (2.5.1+cpu) are installed from the PyTorch CPU index by the Dockerfile."
    printf '%s\n' "$out" | sed -n '/^=== MAIN$/,$p' | grep -v '^==='
  } > "$HERE/requirements.lock.new"
  mv "$HERE/ort-floor.lock.new" "$HERE/ort-floor.lock"
  mv "$HERE/requirements.lock.new" "$HERE/requirements.lock"
  echo "wrote $HERE/requirements.lock ($(grep -c -v '^#' "$HERE/requirements.lock") pins) and $HERE/ort-floor.lock"
}

CTX_DIR=""
trap '[ -z "$CTX_DIR" ] || rm -rf "$CTX_DIR"' EXIT

build() {
  CTX_DIR="$(mktemp -d)"
  cp "$HERE/Dockerfile" "$HERE/requirements.lock" "$HERE/ort-floor.lock" "$CTX_DIR/"
  cp "$CODE_DIR/export_checkpoint.py" "$CODE_DIR/train_rfdetr.py" "$CODE_DIR/_common.py" "$CTX_DIR/"
  # linux/amd64 explicitly (SageMaker ml.m5 hosts). Docker: buildx with
  # --provenance=false, so the pushed tag is a plain image manifest rather
  # than an index carrying an attestation (SageMaker expects the former).
  # podman (often installed as `docker`): buildah, which writes no attestation.
  if "$ENGINE" --version 2>/dev/null | grep -qi podman; then
    "$ENGINE" build --platform linux/amd64 -t "$ECR_REPO:$TAG" "$CTX_DIR"
  else
    "$ENGINE" buildx build --platform linux/amd64 --provenance=false --load \
      -t "$ECR_REPO:$TAG" "$CTX_DIR"
  fi
  echo "built $ECR_REPO:$TAG"
}

push() {
  if [ -z "$AWS_ACCOUNT_ID" ]; then
    AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
  fi
  local registry="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
  local uri="$registry/$ECR_REPO"
  build
  aws ecr get-login-password --region "$AWS_REGION" | "$ENGINE" login --username AWS --password-stdin "$registry"
  "$ENGINE" tag "$ECR_REPO:$TAG" "$uri:$TAG"
  "$ENGINE" push "$uri:$TAG"
  local digest
  digest="$(aws ecr describe-images --region "$AWS_REGION" --repository-name "$ECR_REPO" \
    --image-ids imageTag="$TAG" --query 'imageDetails[0].imageDigest' --output text)"
  echo "pushed $uri:$TAG"
  echo "detectorExportImage=$uri@$digest"
}

case "$MODE" in
  lock) lock ;;
  build) build ;;
  push) push ;;
esac
