find_package(Swig)

function(SWIG)
    cmake_parse_arguments("" "" "LANGUAGE;FILE;MODULE_NAME" "DEPENDS;AUTOGEN_PATCH" ${ARGN})

    # argument validation
    if(NOT DEFINED _FILE)
        message(FATAL_ERROR "Swig input file must be specified")
    endif()

    if(NOT EXISTS ${_FILE})
        message(FATAL_ERROR "Could not find file ${_FILE}")
    endif()

    if(NOT DEFINED _LANGUAGE)
        message(FATAL_ERROR "Language must be specified")
    endif()

    # If module name is not defined, assume it is the file name
    if(NOT DEFINED _MODULE_NAME)
        get_filename_component(FILE_NAME ${_FILE} NAME_WE)
        set(_MODULE_NAME ${FILE_NAME})
    endif()

    # Setting flags and arguments
    if(${_LANGUAGE} STREQUAL "python")
        set(LANG_FLAG "-python")
        set(LANG_EXT "py")
        set(WORKING_DIR_SUFFIX "/python")
    else()
        message(FATAL_ERROR "${_LANG} is not currently supported")
    endif()

    # Create directory that will hold the autogenerated files
    set(DIR "${SWIG_AUTOGEN_DIR}/${WORKING_DIR_SUFFIX}")
    file(MAKE_DIRECTORY "${DIR}")
    
    set(GENERATED_FILES
      "${DIR}/${_MODULE_NAME}.${LANG_EXT}"
      "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/${_MODULE_NAME}.${LANG_EXT}"
      "${DIR}/${_MODULE_NAME}_wrap.cxx"
      "${DIR}/${_MODULE_NAME}_wrap.h"
    )

    # Use powershell to copy on Windows
    if(MSVC)
        set(COPY_PREFIX "powershell")
        set(POWERSHELL "powershell")
    else()
        set(COPY_PREFIX "")
        set(POWERSHELL "pwsh")
    endif()

    set(COPY_DIR ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})

    # Generate runtime header files
    set(RUNTIME_HEADER "${_MODULE_NAME}_${_LANGUAGE}_runtime.h")
    add_custom_command(
        OUTPUT ${RUNTIME_HEADER}
        COMMAND ${Swig_EXE} ${LANG_FLAG} -external-runtime ${RUNTIME_HEADER}
        WORKING_DIRECTORY "${DIR}"
    )

    add_custom_target("${_MODULE_NAME}_${_LANGUAGE}_runtime" ALL
        WORKING_DIRECTORY "${DIR}"
        DEPENDS ${RUNTIME_HEADER})

    # Targets in _DEPENDS may depend on runtime header, so add RUNTIME_HEADER target as a dependency to them
    foreach(dependency ${_DEPENDS})
        add_dependencies(${dependency} "${_MODULE_NAME}_${_LANGUAGE}_runtime")
    endforeach()

    # Generate projections
    set(PROJECTION_TARGET "${_MODULE_NAME}_${_LANGUAGE}_projection")
    add_custom_command(
        OUTPUT ${GENERATED_FILES}
        COMMAND ${Swig_EXE} ${LANG_FLAG} -threads -outcurrentdir -I"${PROJECT_SOURCE_DIR}/include" -c++ ${_FILE}
        COMMAND ${COPY_PREFIX} cp ${DIR}/${_MODULE_NAME}.${LANG_EXT} ${COPY_DIR}
        WORKING_DIRECTORY "${DIR}"
        DEPENDS ${_FILE})
    
    add_custom_target(${PROJECTION_TARGET} ALL
        WORKING_DIRECTORY "${DIR}"
        DEPENDS ${GENERATED_FILES})

    if(MSVC)
        #workaround for bug in windows around xmemory
        set(CORECRT_TARGET_NAME "CORECRT_${_MODULE_NAME}_${_LANGUAGE}")
        add_custom_target(${CORECRT_TARGET_NAME} ALL
            WORKING_DIRECTORY  "${DIR}"
            COMMAND powershell "'#include <corecrt.h>' + (Get-Content ${DIR}/${_MODULE_NAME}_wrap.cxx -Raw) | Set-Content ${DIR}/${_MODULE_NAME}_wrap.cxx"
            DEPENDS "${DIR}/${_MODULE_NAME}_wrap.cxx"
        )

        add_dependencies(${CORECRT_TARGET_NAME} "${_MODULE_NAME}_${_LANGUAGE}_projection")
    endif()

    # Apply patches
    # todo: Make this so they don't need to be compiled each time
    string(JOIN "," PatchFiles ${_AUTOGEN_PATCH})
    if(DEFINED _AUTOGEN_PATCH)
            add_custom_target(SWIG_PATCH ALL
                WORKING_DIRECTORY  "${DIR}"
                COMMAND ${POWERSHELL} ${CMAKE_CURRENT_SOURCE_DIR}/autogen_patches/patch.ps1 -PatchFiles ${PatchFiles} -Destination ${DIR}/${_MODULE_NAME}_wrap.cxx
                DEPENDS "${DIR}/${_MODULE_NAME}_wrap.cxx" 
            )

            add_dependencies(SWIG_PATCH ${CORECRT_TARGET_NAME} "${_MODULE_NAME}_${_LANGUAGE}_projection")
    endif()
    
    set(TARGET_NAME "${_MODULE_NAME}_${_LANGUAGE}")
    add_compile_definitions(SWIG_PYTHON_INTERPRETER_NO_DEBUG)
    add_library(${TARGET_NAME} SHARED "${DIR}/${_MODULE_NAME}_wrap.cxx")
    add_dependencies(${TARGET_NAME} ${PROJECTION_TARGET} SWIG_PATCH)
    
    if(MSVC)
        add_dependencies(${TARGET_NAME} ${CORECRT_TARGET_NAME})
    endif()

    target_link_directories(${TARGET_NAME} PRIVATE ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib)
    if(MSVC)
        set_target_properties(${TARGET_NAME} PROPERTIES SUFFIX ".pyd")
    endif()
    set_target_properties(${TARGET_NAME} PROPERTIES OUTPUT_NAME "_${_MODULE_NAME}")
    set_target_properties(${TARGET_NAME} PROPERTIES PREFIX "")

    if(MSVC)
        target_link_libraries(${TARGET_NAME} ${Python3_LIBRARIES} ${_DEPENDS})
    else()
        target_link_libraries(${TARGET_NAME} ${Python3_LIBRARIES} ${_DEPENDS})
    endif()
endfunction()