# Copyright 2025 Amazon Web Services, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Preservation baseline: the distro/system-python coupling is UNCHANGED (Req 3.1, 3.6).

Spec: python-3-11-security-upgrade — Property 2: Preservation — No functional
regression for non-3.9 artifacts.

The interpreter upgrade moves the **DDA** interpreter from 3.9 to 3.11. Two
distro/system-python dependencies are deliberately NOT part of the bug and must
survive the fix unchanged (``F(X) = F'(X)`` for these non-bug artifacts):

* **`g-ir-scanner` system-python shebang (Req 3.1).** Aravis/`gi` typelibs are
  generated by ``g-ir-scanner``, whose ``_giscanner`` C extension is built for the
  *distro* python (3.8 on the JP5 focal base, 3.10 on the JP6 jammy base) — NOT the
  DDA python. The backend Dockerfiles force its shebang at the distro python; that
  must remain pinned to the distro python (never the DDA interpreter) before and
  after the fix.
* **Host model-conversion `python3` (Req 3.6).** The Greengrass model component
  runs ``python3 /aws_dda/model_convertor.py`` / ``convert_model_cleanup.py`` on the
  HOST using the **system** ``python3`` (not a versioned DDA interpreter); the
  provisioning scripts install that script's deps onto the bare system ``python3``.
  That coupling must remain on the system ``python3``.

These assertions are written so they hold on BOTH the UNFIXED (3.9) tree (task 2)
and the FIXED (3.11) tree (task 11): they pin the distro-python invariants that are
constant across the migration, never the DDA-version text that legitimately changes.

**Validates: Requirements 3.1, 3.6**

Runs in a bare checkout (reads repo files only):

    python3 -m pytest test/backend-test/preservation/test_preservation_distro_python.py \\
        --noconftest -v
"""
import os
import re

# repo root = test/backend-test/preservation/<this file> -> up 4 levels.
REPO_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)


def _read(rel: str) -> str:
    with open(os.path.join(REPO_ROOT, rel), "r", encoding="utf-8", errors="replace") as fh:
        return fh.read()


# --------------------------------------------------------------------------- #
# Req 3.1 — g-ir-scanner stays pinned to the distro/system python
# --------------------------------------------------------------------------- #
# Spec: python-3-11-security-upgrade — Property 2: Preservation
# Validates: Requirements 3.1
def test_jp5_g_ir_scanner_shebang_is_system_python38_unchanged():
    """JP5 g-ir-scanner shebang stays the distro python (``/usr/bin/python3.8``).

    The ``_giscanner`` C extension on the focal base is built for the system 3.8;
    the shebang must remain 3.8 and must never become the DDA interpreter.

    Validates: Requirements 3.1
    """
    content = _read("src/backend/Dockerfile.jp5")

    # The distro-python shebang the Dockerfile writes into /usr/bin/g-ir-scanner.
    assert "#!/usr/bin/python3.8" in content, (
        "JP5 g-ir-scanner system-python (3.8) shebang must be preserved"
    )

    # The shebang line itself must target the system python, never the DDA python.
    shebang_lines = re.findall(r"#!/usr/bin/python3\.\d+", content)
    assert shebang_lines, "expected a g-ir-scanner shebang line in Dockerfile.jp5"
    for line in shebang_lines:
        assert line == "#!/usr/bin/python3.8", (
            f"g-ir-scanner shebang must stay distro python3.8, found {line!r}"
        )


# Spec: python-3-11-security-upgrade — Property 2: Preservation
# Validates: Requirements 3.1
def test_jp6_g_ir_scanner_uses_dynamic_system_python_unchanged():
    """JP6 g-ir-scanner stays bound to the dynamically-detected distro python.

    The shebang is ``#!$SYS_PY`` (the detected system python) with a
    ``/usr/bin/python3.10`` fallback — never a hardcoded DDA-version shebang.

    Validates: Requirements 3.1
    """
    content = _read("src/backend/Dockerfile.jp6")

    # Dynamic system-python detection + jammy fallback are preserved.
    assert "/usr/bin/python3.10" in content, (
        "JP6 g-ir-scanner system-python (3.10) fallback must be preserved"
    )
    assert 'echo "#!$SYS_PY" > /usr/bin/g-ir-scanner' in content, (
        "JP6 g-ir-scanner must keep using the dynamically-detected system python ($SYS_PY)"
    )

    # The shebang must NOT be hardcoded to any DDA interpreter version.
    assert "#!/usr/bin/python3.9" not in content, (
        "JP6 g-ir-scanner shebang must not be hardcoded to the (old) DDA python 3.9"
    )
    assert "#!/usr/bin/python3.11" not in content, (
        "JP6 g-ir-scanner shebang must not be hardcoded to the DDA python 3.11"
    )


# --------------------------------------------------------------------------- #
# Req 3.6 — host model-conversion scripts stay on the system python3
# --------------------------------------------------------------------------- #
# Spec: python-3-11-security-upgrade — Property 2: Preservation
# Validates: Requirements 3.6
def test_patch_host_prereqs_keeps_system_python3_for_model_conversion():
    """``patch_docker_host_prereqs.sh`` keeps the system ``python3`` model path.

    The model-conversion Startup/Shutdown scripts run on the bare system
    ``python3`` and their deps are installed via ``ensure_host_py_deps python3``.

    Validates: Requirements 3.6
    """
    content = _read("station_install/patch_docker_host_prereqs.sh")

    # Host model-conversion runs on the system python3 (documented + invoked).
    assert "python3 /aws_dda/model_convertor.py" in content, (
        "host model_convertor.py must run on the system python3"
    )
    assert "ensure_host_py_deps python3" in content, (
        "system python3 must be patched for the model-conversion scripts"
    )


# Spec: python-3-11-security-upgrade — Property 2: Preservation
# Validates: Requirements 3.6
def test_setup_station_keeps_system_python3_for_model_conversion():
    """``setup_station.sh`` keeps the system ``python3`` model-conversion deps.

    The model-conversion scripts are invoked with the bare system ``python3`` and
    their protobuf/requests deps are installed onto it (not a versioned DDA python).

    Validates: Requirements 3.6
    """
    content = _read("station_install/setup_station.sh")

    # Model-conversion scripts run on the system python3 (documented).
    assert "python3 /aws_dda/model_convertor.py" in content, (
        "host model_convertor.py must run on the system python3"
    )
    assert "python3 /aws_dda/convert_model_cleanup.py" in content, (
        "host convert_model_cleanup.py must run on the system python3"
    )

    # The model-conversion deps are installed onto the bare system python3.
    assert 'python3 -c "from google.protobuf.internal import builder"' in content, (
        "system python3 protobuf check for the model-conversion script must be preserved"
    )
    assert re.search(r"python3 -m pip install .*protobuf", content), (
        "system python3 protobuf install for model conversion must be preserved"
    )

    # The explicit "do NOT change the system python3" intent must remain.
    assert "do NOT change the system python3" in content or \
        "Do NOT change the system python3" in content, (
        "the 'do NOT change the system python3' guard must be preserved"
    )
